Add a class method
We define a class method in Ruby by adding a `self.` keyword before the method name in the definition. We call it a class method because we call this directly on the class without instantiating a variable as in:
```ruby
Cookie.info
```
If you try to call it on an object, also called instance, then you will get an error:
```ruby
c = Cookie.new
c.info
```
will give you:
```shell
NoMethodError: undefined method `info' for #<Cookie:0x0000010411b9a8>
```